version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_peliculas
    restart: always
    environment:
      POSTGRES_DB: pelicula
      POSTGRES_USER: pelicula
      POSTGRES_PASSWORD: pelicula
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./create_database.sql:/docker-entrypoint-initdb.d/1_create_database.sql:ro
      - ./insert_data.sql:/docker-entrypoint-initdb.d/2_insert_data.sql:ro
      - ./update_usuario_password.sql:/docker-entrypoint-initdb.d/3_update_usuario_password.sql:ro
volumes:
  db_data:
